### ISSUE TITLE
Working prototype

### ISSUE THREAD

**Issue by jnewland** [jnewland/airfoil-api-smartthings#1]
- [x] Service Manager / install app
- [x] Device Handler
### References
- https://github.com/SmartThingsCommunity/SmartThingsTest/blob/241094028dceab387a4325ebf2478ce957d267d5/devicetypes/smartthings/hue-lux-bulb.groovy
- https://github.com/SmartThingsCommunity/SmartThingsTest/blob/241094028dceab387a4325ebf2478ce957d267d5/smartapps/smartthings/hue-connect.groovy

**Comment by ijaspley** [comment]
Hi, I managed to resolve the issue with airfoil-api, there was a problem with mdns, so I took it out of the dependencies and added it from nam directly.

I am having a new problem with the smart app for it.

Quite simply it finds my Airfoil speakers but keeps giving a red banner 'Error saving page' at the top when I press done. Is this resolvable at all?

Thanks
